CREATE TABLE IF NOT EXISTS rating (
              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              name varchar(7) NOT NULL,
              description varchar(200)
          );

CREATE TABLE IF NOT EXISTS genre (
              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              name varchar(25) NOT NULL,
              description varchar(200)
          );

CREATE TABLE IF NOT EXISTS film (
              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              name varchar(200) NOT NULL,
              description varchar(200) NOT NULL,
              duration integer,
              release_date date,
              mpa BIGINT REFERENCES rating(id) ON DELETE RESTRICT
          );

CREATE TABLE IF NOT EXISTS users (
              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              email varchar(50) NOT NULL,
              login varchar(15) NOT NULL,
              name varchar(200) NOT NULL,
              birthday date
          );

CREATE TABLE IF NOT EXISTS film_genre (
              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              film_id BIGINT NOT NULL REFERENCES film(id) ON DELETE CASCADE,
              genre_id BIGINT NOT NULL REFERENCES genre(id) ON DELETE CASCADE
          );

CREATE TABLE IF NOT EXISTS likes (
              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              film_id BIGINT NOT NULL REFERENCES film(id) ON DELETE CASCADE,
              user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE
          );

CREATE TABLE IF NOT EXISTS friends (
              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              user1_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
              user2_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE
          );